import type { Comment, Project, Task, User } from "./domain";

export const users: User[] = [
  {
    id: "user-pontus",
    name: "Pontus Ling",
    email: "pontus@example.com",
  },
  {
    id: "user-maya",
    name: "Maya Chen",
    email: "maya@example.com",
  },
  {
    id: "user-leo",
    name: "Leo Andersson",
    email: "leo@example.com",
  },
];

export const projects: Project[] = [
  {
    id: "project-website",
    name: "Website Redesign",
    description: "Refresh the company marketing site and improve conversion paths.",
    color: "violet",
    createdAt: "2026-09-01",
  },
  {
    id: "project-mobile-app",
    name: "Mobile App Launch",
    description: "Prepare the first release of the customer mobile application.",
    color: "sky",
    createdAt: "2026-09-05",
  },
  {
    id: "project-brand",
    name: "Brand Refresh",
    description: "Apply the updated visual identity across customer touchpoints.",
    color: "emerald",
    createdAt: "2026-09-10",
  },
];

export const tasks: Task[] = [
  {
    id: "task-homepage-design",
    projectId: "project-website",
    title: "Create homepage design",
    description: "Create the final desktop and mobile homepage layouts.",
    status: "in-progress",
    priority: "high",
    assigneeId: "user-pontus",
    dueDate: "2026-09-23",
    createdAt: "2026-09-12",
    updatedAt: "2026-09-22",
  },
  {
    id: "task-copy-review",
    projectId: "project-website",
    title: "Review homepage copy",
    description: "Check the approved copy against the new page structure.",
    status: "review",
    priority: "medium",
    assigneeId: "user-maya",
    dueDate: "2026-09-24",
    createdAt: "2026-09-14",
    updatedAt: "2026-09-21",
  },
  {
    id: "task-analytics-setup",
    projectId: "project-website",
    title: "Set up analytics events",
    description: "Document and implement the conversion events for the new site.",
    status: "todo",
    priority: "low",
    assigneeId: "user-leo",
    dueDate: "2026-09-29",
    createdAt: "2026-09-18",
    updatedAt: "2026-09-18",
  },
  {
    id: "task-design-system",
    projectId: "project-website",
    title: "Define design tokens",
    description: "Document the initial color, spacing, and typography tokens.",
    status: "done",
    priority: "medium",
    assigneeId: "user-pontus",
    dueDate: "2026-09-18",
    createdAt: "2026-09-08",
    updatedAt: "2026-09-18",
  },
  {
    id: "task-onboarding-flow",
    projectId: "project-mobile-app",
    title: "Build onboarding flow",
    description: "Implement the first-run screens and account setup journey.",
    status: "in-progress",
    priority: "high",
    assigneeId: "user-maya",
    dueDate: "2026-09-26",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-22",
  },
  {
    id: "task-push-notifications",
    projectId: "project-mobile-app",
    title: "Plan notification preferences",
    description: "Define the notification settings and their default values.",
    status: "todo",
    priority: "medium",
    createdAt: "2026-09-19",
    updatedAt: "2026-09-19",
  },
  {
    id: "task-accessibility-audit",
    projectId: "project-brand",
    title: "Run accessibility audit",
    description: "Audit the new brand palette and core components for accessibility.",
    status: "review",
    priority: "high",
    assigneeId: "user-leo",
    dueDate: "2026-09-21",
    createdAt: "2026-09-09",
    updatedAt: "2026-09-20",
  },
  {
    id: "task-social-templates",
    projectId: "project-brand",
    title: "Create social media templates",
    description: "Create reusable templates for launch announcements and updates.",
    status: "done",
    priority: "low",
    assigneeId: "user-maya",
    dueDate: "2026-09-17",
    createdAt: "2026-09-06",
    updatedAt: "2026-09-17",
  },
];

export const comments: Comment[] = [
  {
    id: "comment-homepage-1",
    taskId: "task-homepage-design",
    authorId: "user-maya",
    body: "The mobile navigation design is ready for review.",
    createdAt: "2026-09-22",
  },
  {
    id: "comment-onboarding-1",
    taskId: "task-onboarding-flow",
    authorId: "user-pontus",
    body: "Please keep the first-run flow to three screens where possible.",
    createdAt: "2026-09-22",
  },
];
